---
title: "Publications"
#author: "Samuel J. L. Gascoigne"
#date: "2023-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>

body {
text-align: justify;
font-size: 12pt;
}

h2, h3 {
  text-align: right;
}

</style>

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>

<br>

**Manuscripts: 28 total, 13 published, 15 under review**

**[Google Scholar](https://scholar.google.com/citations?user=vQzYzlAAAAAJ&hl=en): h-index = 6**

**Also see profiles on [ResearchGate](https://www.researchgate.net/profile/Samuel-Gascoigne), [Web of Science](https://www.webofscience.com/wos/author/record/ITV-8261-2023?state=%7B%7D) and [ORCID](https://orcid.org/0000-0002-2984-1810)**


**# = shared first authorship**

<br>

<span style="color: #8B0000;"><em><strong>For more details on each publication and a downloadable pdf, click on the triangle beside each reference.</em></strong></span>

---

<br>


## Under review

<br>

<details>
  <summary>
  
  28| Gupta A, **Gascoigne SJL**, Barabás G, Qi M, Fenollosa E, Thornley R, Hernández C, Hector A, Salguero-Gómez R. Variation in precipitation drives differences in short-term transient instability between grassland functional groups: A stage structured community approach. *Ecology Letters*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2024.10.07.617067v1))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study shows how precipitation can lead to transient instability in grassland communities.*</span>

<br>

<object data="publications/Gupta et al. 2024.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>

</details>

<br>

<details>
  <summary>
  
  27| Li D, Hu Y, Salguero-Gómez R, **Gascoigne SJL**, Qing W, Meisi R, Weiwei X, Wei W, Haitao M, Li S. Clonal integration differentially impacts grassland plants under simulated homogeneous and heterogeneous grazing. *Journal of Applied Ecology*. Under review.
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study shows that clonal integration and heterogenous grazing behaviours can lead to increased productivity in a grassland species.*</span>


</details>

<br>

<details>
  <summary>
  
  26| Sanghvi K, **Gascoigne SJL**, Todorova B, Vega-Trejo R, Pizzari T, Sepil I. No evidence for paternal age effects on sons or
daughters, when accounting for paternal sperm storage. *Functional Ecology*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2024.09.19.613916v1.abstract))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study implicates sperm age as a primary driver of male age related declines in sperm performance in Drosophila melanogaster.*</span>

<br>

<object data="publications/Sanghvi et al. 2024 sperm age.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>

</details>

<br>

<details>
  <summary>
  
  25| Santos GS, Yang X, **Gascoigne SJL**, Compagnoni A, Dias ATC, Tuljapurkar S, Kajin M, Salguero-Gómez R. Population responses to environmental stochasticity are primarily driven by survival-reproduction trade-offs and mediated by aridity. *Nature*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2024.07.24.604949v1))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study builds on previous work using the summation of stochastic elasticities of variance. Here, we show demographic buffering is driven by life history trade-offs and degree of climate aridity.*</span>

<br>

<object data="publications/Santos et al. 2024.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
  
</details>


<br>

<details>
  <summary>
  
  24| Sanghvi K, Shandilya S, Brown A, Todorova B, Jahn M, **Gascoigne SJL**, Camilleri TL, Pizzari T, Sepil I. Reproductive output of old polygynous males is limited by seminal fluid, not sperm number. *Proceedings of the National Academy of Sciences*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2024.07.02.601670v1))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study demonstrates that seminal fluid is the limiting resource for multiple mating males - not sperm number.*</span>

<br>

<object data="publications/Sanghvi et al. 2024 seminal fluid.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
  
</details>

<br>

<details>
  <summary>
  
  23| Xiao-Lu ST, Yu-Kun H, Katriona S, **Gascoigne SJL**, Qing W, Li-Chen T, Dan-Dan L, Li SL. Germination time affects the responses of seedlings to variation in rainfall. *Annals of Botany*. Under review.
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Our study demonstrates that germination timing may strongly affect the responses of seedlings to rainfall variation, suggesting that plants with flexible germination timing may better adapt to rainfall fluctuations, and thus more suitable for desert vegetation restoration under climate change. *</span>

<br>
  
</details>

<br>

<details>
  <summary>
  
  22| Noble DWA, Zoe A, Xirocostas ZA, Wu NC, Martinig AR, Almeida RA, Bairos-Novak KR, Heikel Balti H, Bertram MG, Bliard L, Brand JA, Byrne I, Chan YC, Clink DJ, Corbel Q, Correia RA, Crawford-Ash J, Culina A, D’Bastiani E, Deme GG, de Souza Leite M, Dhellemmes F, Dimri S, Drobniak SM, Elsy AD, Everingham SE, **Gascoigne SJL**, Grainger MJ, Hossack GC, Hovstad KA, Ivimey-Cook ER, Jones ML, Kačergytė I, Küstner G, Leibold DC, Mair MM, Martin J, Mizuno A, Moodie IR, Moreau D, O’Dea RE, Orr JA, Paquet M, Parajuli R, Pick JL, Pottier P, Purgar M, Recio P, Roche DG, Royauté R, Sabet SS, Segovia JMG, Silva I, Sánchez-Tójar A, Soares BE, Szabo B, Takola E, Thoré ESJ, Timilsina B, van Dis NE, Verberk WCEP, Vriend SJG, Wild KH, Williams C, Yang Y, Nakagawa S, Malgorzata Lagisz M. The promise of community-driven preprints in ecology and evolution. *Proceedings of the Royal Society B*. Under review. ([preprint link](https://ecoevorxiv.org/repository/view/7239/))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Here, we explore the first preprints uploaded to EcoEvoRxiv to characterise preprint practices in ecology and evolution.*</span>

<br>
  
  <object data="publications/Noble et al. 2024.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>

<details>
  <summary>
  
  21| **Gascoigne SJL**, Kajin M, Sepil I, Salguero-Gómez R. Testing for efficacy in four measures of demographic buffering. *Methods in Ecology & Evolution*. Under review. ([preprint link](https://ecoevorxiv.org/repository/view/7207/))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Here, we show how the summation of stochastic elasticities of variance is an effective measure of demographic buffering using four environmentally explicit integral projection models (IPMs) and a series of counterfactual simulations.*</span>

<br>
  
  <object data="publications/Gascoigne et al. 2024 Efficacy.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>

<details>
  <summary>
  
  20| Huang Y, Wu C, Huang W, Liu Y, Qi M, Bai J, Dong Y, **Gascoigne SJL**, Ciais P, Peñuelas J, Salguero-Gómez R. Climate change has desynchronized insect and vegetation phenologies across Europe. *Nature Communications*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2023.12.11.571152v1.abstract))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Here, we show how climate change is increasing the asynchrony of phenologies of plant and insect species across Europe. This asynchrony is structured across taxa, life history and well as latitude.*</span>

<br>
  
  <object data="publications/Huang et al. 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>


<details>
  <summary>
  
  19| Tuljapurkar SD, Jaggi H, **Gascoigne SJL**, Zuo W, Kajin M, Salguero-Gómez R. From disturbances to nonlinear fitness and back. *Ecology*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2023.10.20.563360v2.abstract))
  
  </summary>
  <br>
  
  <span style="color: #8B0000;">*Here, we identify an intimate relationship between the responses of structured populations to pulse and press disturbance and their associated second derivatives of \lambda with respect to demographic rates.*</span>

<br>
  
  <object data="publications/Tulja et al 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>







<details>

  <summary>
  
  18| **Gascoigne SJL**, Rosen A, Sanghvi K, Compagnoni A, Steiner UK, Bocedi G, Sepil I. Current perspectives and future directions in animal life history evolution. *Journal of Animal Ecology*. Under review. ([preprint link](https://www.authorea.com/users/657075/articles/670780-current-perspectives-and-future-directions-in-animal-life-history-evolution))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we both review the current state of research in animal life history evolution and offer three new research programs that address specific gaps in knowledge.*</span>

<br>
  
  <object data="publications/Gascoigne et al. 2023 Current perspectives.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>






<details>

  <summary>
  
  17| Uwera Nalukwago D, **Gascoigne SJL**, DeFoe B, Barbosa F. A proximate mechanism for evolutionary trade-offs in the bean beetle Callosobruchus maculatus. *Evolution*. Under review.
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we show how juvenile hormone underlies the generation of density-dependent dispersal morph generation in the bean beetle, Callosobruchus maculatus.*</span>

<br>
  
  
</details>

<br>





<details>

  <summary>
  
  16| **Gascoigne SJL**, Kajin M, Tuljapurkar SD, Santos GS, Compagnoni A, Steiner UK, Vinton AC, Jaggi H, Sepil I, Salguero-Gómez R. Structured demographic buffering: A framework to explore the environment drivers and demographic mechanisms underlying demographic buffering. *Ecology Letters*. Under review.  ([preprint link](https://www.biorxiv.org/content/10.1101/2023.07.20.549848v1.abstract))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we use environment stochastic integral projection models to show how environment components impact demographic buffering by different mechanisms.*</span>

<br>
  
  <object data="publications/Gascoigne et al. 2023 Structured demographic buffering.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>








<details>

  <summary>
  
  15| Santos GS #, **Gascoigne SJL #**, Dias ATC, Kajin M, Salguero-Gómez R. A unified framework to identify demographic buffering in natural populations. *Ecology Letters*. Under review. ([preprint link](https://www.biorxiv.org/content/10.1101/2023.07.03.547528v1.abstract))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we propose a new framework to quantify demographic buffering.*</span>

<br>
  
  <object data="publications/Santos et al. 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>






<details>

  <summary>
  
  14| Veit W, **Gascoigne SJL**, Salguero-Gómez R. Evolution, complexity, and life history theory. *Biological Theory*. Under review.  ([preprint link](http://philsci-archive.pitt.edu/21810/))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we begin the philosophical argument for a new approach to quantify life history complexity in structured population models.*</span>

<br>
  
  <object data="publications/Veit et al. 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<br>


---

<br>

## 2024

<br>

<details>

  <summary>
  
  13| Sanghvi K, Vega-Trejo R, Nakagawa S, **Gascoigne SJL**, Johnson S, Salguero-Gómez R, Pizzari T, Sepil I. 2024. No consistent declines in ejaculate traits with advancing male age across animals: a meta-analysis. *Nature Communications*. *15*(558).  ([link](https://www.nature.com/articles/s41467-024-44768-4))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we perform a meta-analysis testing the presence of senescence in ejaculate traits across non-human animals.*</span>

<br>
  
  <object data="publications/Sanghvi et al. 2024.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41467-024-44768-4" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1038/s41467-024-44768-4" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>


<details>

  <summary>
  
  12| **Gascoigne SJL**, Kajin M, Salguero-Gómez R. 2024. Criteria for buffering in ecological modelling. *Trends in Ecology & Evolution*. *39*(2), 116-118. ([link](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(23)00323-3))  




</summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we propose and argue for a set of necessary criteria for the determination of a buffering mechanism in ecological modelling.*</span>

<br>
  
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.tree.2023.11.006" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1016/j.tree.2023.11.006" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<br>

---

<br>



## 2023



<details>

  <summary>
  
  11| Wood A, **Gascoigne SJL**, Gambetta G, Jeffers L, Coulson T. 2023. Seasonal climate impacts wine quality in Bordeaux. *iScience*, *26*(107954). ([link](https://www.sciencedirect.com/science/article/pii/S258900422302031X), also see media coverage: [The Times](https://www.thetimes.co.uk/article/raise-a-glass-to-climate-change-until-you-can-t-gxpqlz3ks), [The Independent](https://www.independent.co.uk/news/science/bordeaux-andrew-wood-weather-university-of-oxford-france-b2427992.html), [Evening Standard](https://www.standard.co.uk/news/science/bordeaux-weather-university-of-oxford-france-experts-b1112881.html), [Daily Mail](https://www.dailymail.co.uk/sciencetech/article-12619357/Climate-change-making-wine-taste-BETTER-Warm-summers-wet-winters-yield-better-quality-vintages-study-finds.html), [National Geographic](https://www.nationalgeographic.com/environment/article/climate-change-french-wine-taste-better), [New Scientist](https://www.newscientist.com/article/2396693-climate-change-may-be-improving-the-quality-of-bordeaux-wines/) and many more) 
  
  <!-- <div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.isci.2023.107954" data-hide-no-mentions="true" class="altmetric-embed" style="text-align: right" ></div> -->

  <!-- <span class="__dimensions_badge_embed__" data-doi="10.1016/j.isci.2023.107954" data-style="small_circle" style="text-align: right"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script> -->
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we show how seasonal climate has broad impacts on wine quality in Bordeaux.*</span>

<br>
  
  <object data="publications/Wood et al. 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.isci.2023.107954" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1016/j.isci.2023.107954" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  10| **Gascoigne SJL**, Rolph S, Sankey D, Nidadavolu N, Stell Pičman AS, Hernandez CM, Philpott MER, Salam A, Bernard C, Fenollosa E, Lee YJ, McLean J, Hetti Achchige Perera S, Spacey OG, Kajin M, Vinton AC, Archer CR, Burns JH, Buss DL, Caswell H, Che-Castaldo JP, Childs DZ, Capdevila P, Compagnoni A, Crone E, Ezard THG, Hodgson D, Knight TM, Jones OR, Jongejans E, McDonald J, Tenhumberg B, Thomas CC, Tyre AJ, Ramula S, Stott I, Tremblay RL, Wilson P, Vaupel JW, Salguero-Gómez R. 2023. A standard protocol to report discrete stage-structured demographic information. *Methods in Ecology & Evolution*, *14*(8), 2065-2083. ([link](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.14164))
  
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we propose a standard protocol for the communication of matrix population models (MPMs), their associated metadata and outline best practices in MPM construction.*</span>

<br>
  
  <object data="publications/Gascoigne et al. 2023 Standard protocol.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/2041-210X.14164" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1111/2041-210X.14164" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  9| Bernard C, Santos GS, Deere J, Rodriguez-Caro R, Capdevila P, Kusch E, **Gascoigne SJL**, Jackson J, Salguero-Gómez R. 2023. MOSAIC: A unified trait database to complement structured population models. *Scientific Data*, *10*(335). ([link](https://www.nature.com/articles/s41597-023-02070-w))


  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we detail a new database containing trait data to contemplate the COMPADRE, COMADRE and PADRINO databases.*</span>

<br>
  
  <object data="publications/Bernard et al. 2023.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41597-023-02070-w" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1038/s41597-023-02070-w" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  8| Vinton AC, **Gascoigne SJL**, Sepil I, Salguero-Gómez R. 2023. The importance of spatial and temporal structure in determining the interplay between plasticity and evolution. *Trends in Ecology & Evolution*, *38*(3), 221-223. ([link](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(22)00335-4))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we respond to [Hoffman and Bridle](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(22)00292-0) discussing the importance of spatial and temporal structure when inferring the adaptive nature of phenotypic plasiticity.*</span>
  
   <span style="color: #8B0000;">*This paper is not open-access but please do reach out if you cannot get access.*</span> 

  
</details>


<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.tree.2022.12.009" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1016/j.tree.2022.12.009" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

---

<br>

## 2022


<br>

<details>

  <summary>
  
  7| Vinton AC, **Gascoigne SJL**, Sepil I, Salguero-Gómez R. 2022. Plasticity’s role in adaptive evolution depends on environmental change components. *Trends in Ecology & Evolution*, *37*(12), 1067-1078. ([link](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(22)00216-6))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we discuss the importance of environment change components (i.e., rate of mean change, variance and autocorrelation) on the evolution of phenotypic plasticity.*</span>

<br>
  
  <object data="publications/Vinton et al. 2022.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.tree.2022.08.008" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1016/j.tree.2022.08.008" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  6| Kapali GP, Callier V, **Gascoigne SJL**, Harrison JF, Shingleton AW. 2022. A steroid hormone regulates growth in response to oxygen availability. *Scientific Reports*, *12*(1), 1-10. ([link](https://www.nature.com/articles/s41598-022-08563-9))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we show how the steroid hormone ecdysone underlies the hypoxic induced changes in body size and development in the fruit fly Drosophila melanogaster.*</span>

<br>
  
  <object data="publications/Kapali et al. 2022.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41598-022-08563-9" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1038/s41598-022-08563-9" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  5| **Gascoigne SJL**, Uwera Nalukwago D, Barbosa F. 2022. Larval density, sex, and allocation hierarchy affect life-history trait covariances in a bean beetle. *The American Naturalist*, *199*(02). ([link](https://www.journals.uchicago.edu/doi/abs/10.1086/717639?journalCode=an))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we show how larval density induces dispersal related trade-offs and covariances in both morphological and behavioural traits in the bean beetle Callosobruchus maculatus.*</span>

<br>
  
  <span style="color: #8B0000;">*This paper is not open-access but please do reach out if you cannot get access.*</span> 
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1086/717639" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1086/717639" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>





---

<br>

## 2021

<br>

<details>

  <summary>
  
  4| Salguero-Gómez R, Jackson J, **Gascoigne SJL**. 2021. Four key challenges in the open-data revolution. *Journal of Animal Ecology*, *90*(9), 2000-2004. ([link](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13567))

  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we build on the recent paper by [Culina et al.](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13388) and argue for the use of FAIR data practices in ecological research.*</span>

<br>
  
  <object data="publications/Salguero-Gomez et al. 2021.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/1365-2656.13567" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.1111/1365-2656.13567" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

---

<br>

## 2020

<br>

<details>

  <summary>
  
  3| Sandler A, Anderson J, Balaram A, Ganev Y, **Gascoigne SJL**, Gimondo C, Palmero B, Quraishi A, Rodriguez A, Said OS, Conrad W. 2020. Decitabine Treatment Demethylates Vast Majority of High-Confidence Differentially Methylated Regions In HCT-116 Colorectal Cancer. *F1000 Research*, *9*(886). ([link](https://f1000research.com/articles/9-886/v1?src=rss&utm_source=researcher_app&utm_medium=referral&utm_campaign=RESR_MRKT_Researcher_inbound))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we use HCT-116 cells to show the degree to which decitabine demethylates CpG regions in proto-oncogenes.*</span>

<br>
  
  <object data="publications/Sandler et al. 2020.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>



---

<br>

## 2018


<br>

<details>

  <summary>
  
  2| McDonald JMC, Ghosh SM, **Gascoigne SJL**, Shingleton AW. 2018. Plasticity through canalization: The contrasting effect of temperature on trait size and growth in Drosophila. *Frontiers in Cell and Developmental Biology*, *6*(156). ([link](https://www.frontiersin.org/articles/10.3389/fcell.2018.00156/full))
    
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we show that thermally plastic and canalized traits have their apparent response to temperature due to an opposite degree of plasticity/canalization and the cell proliferation level.*</span>

<br>
  
  <object data="publications/McDonald et al. 2018.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-doi="10.3389/fcell.2018.00156" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-doi="10.3389/fcell.2018.00156" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

<details>

  <summary>
  
  1| Abeysiriwardena NM, **Gascoigne SJL**, Anandappa A. 2018. Algal bloom expansion increases cyanotoxin risk in food. *Yale Journal of Biology and Medicine*, *91*(2), 129-142. ([link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6020737/))
  
  </summary>
  
  <br>
  
  <span style="color: #8B0000;">*Here, we review the impacts of algal blooms on population health and how global climate change may lead to increased health concerns due to algal bloom expansion.*</span>

<br>
  
  <object data="publications/Abeysiriwardena et al. 2018.pdf" type = "application/pdf" width = "100%" height = "325px" style="box-shadow: 3px 3px 3px gray;">
</object>
  
</details>

<div>  
  <span data-badge-popover="right" data-badge-type="donut" data-pmid="29955218" data-hide-no-mentions="true" class="altmetric-embed" style="float:right; display:inline;"></span> 
  <span class="__dimensions_badge_embed__" data-pmid="29955218" data-style="small_circle" style="float:right; display:inline;"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<br>
<br>
<br>

---

<br>
